//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoActPlugin.Updater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateQuestionForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateQuestionForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeoActPlugin.Updater.UpdateQuestionForm", typeof(UpdateQuestionForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle btnConfirm_Dock {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        internal static System.Drawing.Point btnConfirm_Location {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=334, Height=32}.
        /// </summary>
        internal static System.Drawing.Size btnConfirm_Size {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int btnConfirm_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnConfirm.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update.
        /// </summary>
        internal static string btnConfirm_Text {
            get {
                return ResourceManager.GetString("btnConfirm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle btnDeny_Dock {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=343,Y=3}.
        /// </summary>
        internal static System.Drawing.Point btnDeny_Location {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=334, Height=32}.
        /// </summary>
        internal static System.Drawing.Size btnDeny_Size {
            get {
                object obj = ResourceManager.GetObject("btnDeny.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int btnDeny_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnDeny.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnDeny_Text {
            get {
                return ResourceManager.GetString("btnDeny.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle label1_Dock {
            get {
                object obj = ResourceManager.GetObject("label1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=0}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=680, Height=30}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new update for {0} available. Install it now?.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        internal static System.Drawing.ContentAlignment label1_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label1.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tableLayoutPanel1_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel1_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel1_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel1_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int tableLayoutPanel1_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=686, Height=516}.
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel1_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int tableLayoutPanel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int tableLayoutPanel2_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel2_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel2_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=464}.
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel2_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tableLayoutPanel2_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=680, Height=38}.
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel2_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int tableLayoutPanel2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle webBrowser1_Dock {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=33}.
        /// </summary>
        internal static System.Drawing.Point webBrowser1_Location {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=20, Height=20}.
        /// </summary>
        internal static System.Drawing.Size webBrowser1_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=680, Height=425}.
        /// </summary>
        internal static System.Drawing.Size webBrowser1_Size {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int webBrowser1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
